In [1]:
import numpy as np

In [7]:
a = np.array([1, 45, 78, 90, True, "ok", 90])

In [15]:
a

array(['1', '45', '78', '90', 'True', 'ok', '90'], dtype='<U11')

In [17]:
b = np.array([34, 78, 99.67, 9])
print(b)

[34.   78.   99.67  9.  ]


In [21]:
b[1] = 800

In [23]:
b

array([ 34.  , 800.  ,  99.67,   9.  ])

In [25]:
# duplicates allowed
# homo
# ordered
# mutable


In [27]:
# speed

In [29]:
l1 = list(range(1000000))
a1 = np.array(l1)

In [31]:
import time as t

In [33]:
t.time()

1772011887.131438

In [35]:
# time take by array
start_time = t.time()
newa = a1 * 2
time_arr = t.time() - start_time
print(f"time taken by an array: {time_arr}")


time taken by an array: 0.0015072822570800781


In [37]:
# time take by list
start_time = t.time()
newl = [i*2 for i in l1]
time_list = t.time() - start_time
print(f"time taken by an list: {time_list}")


time taken by an list: 0.11889076232910156


In [39]:
time_list/time_arr

78.87757038911737

In [43]:
a

array(['1', '45', '78', '90', 'True', 'ok', '90'], dtype='<U11')

In [45]:
a[1: 4]

array(['45', '78', '90'], dtype='<U11')

In [51]:
a

array(['1', '45', '78', '90', 'True', 'ok', '90'], dtype='<U11')

In [57]:
a.ndim

1

In [49]:
a.shape

(7,)

In [55]:
a.size

7

In [47]:
# 2d 

In [59]:
arr = np.array([[1, 2, 3], [3, 5, 2], [8, 6, 7], [1, 5, 2]])

In [61]:
arr

array([[1, 2, 3],
       [3, 5, 2],
       [8, 6, 7],
       [1, 5, 2]])

In [63]:
arr.ndim

2

In [65]:
arr.shape

(4, 3)

In [67]:
arr.size

12

In [69]:
arr[1:3, 0:2]

array([[3, 5],
       [8, 6]])

In [71]:
arr

array([[1, 2, 3],
       [3, 5, 2],
       [8, 6, 7],
       [1, 5, 2]])

In [73]:
arr.reshape(2, 6)

array([[1, 2, 3, 3, 5, 2],
       [8, 6, 7, 1, 5, 2]])

In [77]:
arr.reshape(2, 3, 2)

array([[[1, 2],
        [3, 3],
        [5, 2]],

       [[8, 6],
        [7, 1],
        [5, 2]]])

In [75]:
arr.flatten()

array([1, 2, 3, 3, 5, 2, 8, 6, 7, 1, 5, 2])

In [79]:
arr

array([[1, 2, 3],
       [3, 5, 2],
       [8, 6, 7],
       [1, 5, 2]])

In [85]:
arr.reshape(4, 3, -1)

array([[[1],
        [2],
        [3]],

       [[3],
        [5],
        [2]],

       [[8],
        [6],
        [7]],

       [[1],
        [5],
        [2]]])

In [87]:
arr1 = np.array([[1, 2, 3], [3, 5, 2], [8, 6, 7]])
arr2 = np.array([[1, 2, 1], [9, 5, 2], [6, 9, 7]])

In [91]:
arr1, arr2

(array([[1, 2, 3],
        [3, 5, 2],
        [8, 6, 7]]),
 array([[1, 2, 1],
        [9, 5, 2],
        [6, 9, 7]]))

In [89]:
np.linalg.det(arr1)

-52.999999999999986

In [93]:
np.linalg.inv(arr1)

array([[-0.43396226, -0.0754717 ,  0.20754717],
       [ 0.09433962,  0.32075472, -0.13207547],
       [ 0.41509434, -0.18867925,  0.01886792]])

In [95]:
np.linalg.eig(arr1)

EigResult(eigenvalues=array([12.23751293, -1.7344814 ,  2.49696847]), eigenvectors=array([[-0.3003943 , -0.78216395,  0.22141646],
       [-0.36771625,  0.17044833, -0.75679211],
       [-0.8800841 ,  0.59930537,  0.61501256]]))

In [97]:
arr1 @ arr2

array([[ 37,  39,  26],
       [ 60,  49,  27],
       [104, 109,  69]])

In [99]:
np.dot(arr1, arr2)

array([[ 37,  39,  26],
       [ 60,  49,  27],
       [104, 109,  69]])

In [101]:
np.cross(arr1, arr2)

array([[ -4,   2,   0],
       [  0,  12, -30],
       [-21, -14,  36]])

In [103]:
arr1.T

array([[1, 3, 8],
       [2, 5, 6],
       [3, 2, 7]])